#Download Python from DockerHub and use it
FROM 3.9.5-buster

#Set the working directory in the Docker container
WORKDIR /code

#Copy the dependencies file to the working directory
COPY requirements.txt .

#Install the dependencies
RUN pip install -r requirements.txt

#Copy the Flask app code to the working directory
COPY app/ .

#Run the container
CMD [ "python", "./app.py" ]
